#pragma once

#define IDR_ASSET_CLOSE 101
#define IDR_ASSET_LOGO 102
#define IDR_ASSET_MASK_BOTTOM 103
#define IDR_ASSET_MASK_LEFT 104
#define IDR_ASSET_MASK_RIGHT 105
#define IDR_ASSET_MASK_TOP 106
#define IDR_ASSET_MINIMIZE 107
#define IDR_ASSET_PROXIMA_REGULAR 108
#define IDR_ASSET_PROXIMA_SEMIBOLD 109
#define IDR_ASSET_ROUNDED_RECT 110
